### PR TITLE
Add support for "+1"

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Saw many `+1` on PR but did not add reviewed label. This PR supports it :D

### CODE REVIEW

**Comment by balvig** [comment]
Hello there @JuanitoFatas! And welcome :)
Do you have a link to those PRs by any chance?

**Comment by balvig** [comment]
Hello @JuanitoFatas! Thanks for the PR.

...hmmm this a bit confusing, since `:+1:` results in 👍 , but looking over the PRs currently seems like maybe plain `+1` has a slightly different meaning, more like saying "I agree with this" than meaning "I've reviewed it"? 😅

**Comment by JuanitoFatas** [comment]
> more like saying "I agree with this" than meaning "I've reviewed it"?

Aaaah, you're right. Closing 😊

**Comment by balvig** [comment]
I agree that that's probably confusing though 😅

**Pull request closed without merging**
